### ISSUE TITLE
AttributeError: There's no attribute result in fetchAll()

### ISSUE THREAD

**Issue by Tomas0413** [tariqdaouda/pyArango#62]
Hi, I noticed that I get an error if I iterate through the collection and do something that takes more time. 

For example, if I run this (size of the collection about 4000 documents):

```
for doc in cuisineCategories.fetchAll():
   print(doc)
   time.sleep(30)
```

I get this error:

```
Traceback (most recent call last):
  File "get_subject_of2.py", line 127, in <module>
    for doc in cuisineCategories.fetchAll():
  File "/usr/local/lib/python2.7/dist-packages/pyArango/query.py", line 101, in __next__
    v = self[self.currI]
  File "/usr/local/lib/python2.7/dist-packages/pyArango/query.py", line 114, in __getitem__
    if not self.rawResults and (self.result[i].__class__ is not Edge and self.result[i].__class__ is not Document) : 
  File "/usr/local/lib/python2.7/dist-packages/pyArango/query.py", line 127, in __getattr__
    raise  AttributeError("There's no attribute %s" %(k))
AttributeError: There's no attribute result

```

This works fine:

```
for doc in cuisineCategories.fetchAll():
   print(doc)
```

I have a workaround, so it's not a big issue, just wanted to share.

**Comment by Tomas0413** [comment]
```
Name: pyArango
Version: 1.2.8
Summary: An easy to use python driver for ArangoDB with built-in validation
Home-page: https://github.com/tariqdaouda/pyArango
Author: Tariq Daouda
Author-email: tariq.daouda@umontreal.ca
License: ApacheV2
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests, future
```

**Comment by tariqdaouda** [comment]
Hi, Thanks for sharing. I personally routinely use loops on tens of thousands elements and never encountered it.

Under the hood pyArango makes calls for more data using cursors. My guest is that the connection gets closed by the server because the default timeout has elapsed.
You could try increasing it and see if that works: --http.keep-alive-timeout <seconds> ([doc](https://docs.arangodb.com/3.0/Manual/Administration/Configuration/Arangod.html))
